<?php

use App\Http\Controllers\Api\AccessController;
use App\Http\Controllers\Api\AgriculturalResearchAgentController;
use App\Http\Controllers\Api\AiAssistantController;
use App\Http\Controllers\Api\AiController;
use App\Http\Controllers\Api\AiVisionController;
use App\Http\Controllers\Api\AnalyticsController;
use App\Http\Controllers\Api\AnalyticsEventsController;
use App\Http\Controllers\Api\ApiClientController;
use App\Http\Controllers\Api\AuditController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\AuthExtensionController;
use App\Http\Controllers\Api\BeekeepingController;
use App\Http\Controllers\Api\BillingController;
use App\Http\Controllers\Api\CatalogController;
use App\Http\Controllers\Api\CommerceController;
use App\Http\Controllers\Api\CommunicationsController;
use App\Http\Controllers\Api\CropController;
use App\Http\Controllers\Api\CropKnowledgeLibraryBrowseController;
use App\Http\Controllers\Api\DashboardController;
use App\Http\Controllers\Api\DiagnosisController;
use App\Http\Controllers\Api\DiagnosisRequestController;
use App\Http\Controllers\Api\DirectoryController;
use App\Http\Controllers\Api\FarmController;
use App\Http\Controllers\Api\HealthController;
use App\Http\Controllers\Api\InvitationController;
use App\Http\Controllers\Api\JobSeekerController;
use App\Http\Controllers\Api\JobSeekerProfileController;
use App\Http\Controllers\Api\JobsEmployerController;
use App\Http\Controllers\Api\JobsTalentController;
use App\Http\Controllers\Api\LibraryController;
use App\Http\Controllers\Api\MarketingController;
use App\Http\Controllers\Api\MarketplaceAdminController;
use App\Http\Controllers\Api\MarketplaceListingController;
use App\Http\Controllers\Api\MarketplacePublicController;
use App\Http\Controllers\Api\MediaController;
use App\Http\Controllers\Api\MonitoringController;
use App\Http\Controllers\Api\MonitoringLogsController;
use App\Http\Controllers\Api\OperationsController;
use App\Http\Controllers\Api\OrganizationController;
use App\Http\Controllers\Api\PlantAiDiagnosisController;
use App\Http\Controllers\Api\PlatformAdminController;
use App\Http\Controllers\Api\PlatformController;
use App\Http\Controllers\Api\ProductImageController;
use App\Http\Controllers\Api\ProjectController;
use App\Http\Controllers\Api\ProviderStatusController;
use App\Http\Controllers\Api\PublicCropLibraryFileController;
use App\Http\Controllers\Api\PublicFieldCropCultivationController;
use App\Http\Controllers\Api\PublicPlatformController;
use App\Http\Controllers\Api\ReportsController;
use App\Http\Controllers\Api\SoilController;
use App\Http\Controllers\Api\TaskController;
use App\Http\Controllers\Api\TeamController;
use App\Http\Controllers\Api\TrainingController;
use App\Http\Controllers\Api\UserSettingsController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1/health')->group(function (): void {
    Route::get('/live', [HealthController::class, 'live']);
    Route::get('/ready', [HealthController::class, 'ready']);
    Route::get('/', [HealthController::class, 'legacy']);
});

Route::prefix('v1')->group(function (): void {
    Route::prefix('public')->middleware('throttle:60,1')->group(function (): void {
        Route::get('/services', [PublicPlatformController::class, 'serviceCatalog']);
        Route::get('/library/items', [PublicPlatformController::class, 'publishedLibraryItems']);
        Route::get('/library/crop-files', [PublicCropLibraryFileController::class, 'index']);
        Route::get('/library/crop-files/{fileId}/content', [PublicCropLibraryFileController::class, 'content'])->whereNumber('fileId');
        Route::get('/training/courses', [PublicPlatformController::class, 'publishedTrainingCourses']);
        Route::get('/market/listings', [MarketplacePublicController::class, 'listings']);
        Route::get('/market/listings/{listing}', [MarketplacePublicController::class, 'show'])->whereNumber('listing');
        Route::get('/market/categories', [MarketplacePublicController::class, 'categories']);
        Route::get('/market/units', [MarketplacePublicController::class, 'units']);
        Route::get('/field-crops/farming-needs-profile', [PublicFieldCropCultivationController::class, 'farmingNeedsProfile']);
        Route::post('/research-agent/query', [AgriculturalResearchAgentController::class, 'query']);
        Route::post('/research-agent/plan', [AgriculturalResearchAgentController::class, 'plan']);
        Route::post('/research-agent/search', [AgriculturalResearchAgentController::class, 'search']);
        Route::post('/research-agent/validate', [AgriculturalResearchAgentController::class, 'validate']);
        Route::post('/research-agent/synthesize', [AgriculturalResearchAgentController::class, 'synthesize']);
        Route::post('/plant-diagnosis/analyze', [PlantAiDiagnosisController::class, 'analyze']);
    });

    Route::middleware('throttle:20,1')->group(function (): void {
        Route::post('/auth/register', [AuthController::class, 'register']);
        Route::post('/auth/login', [AuthController::class, 'login']);
        Route::post('/auth/accept-invitation', [InvitationController::class, 'accept']);
        Route::post('/auth/forgot-password', [AuthExtensionController::class, 'forgotPassword'])->middleware('throttle:5,1');
        Route::post('/auth/reset-password', [AuthExtensionController::class, 'resetPassword'])->middleware('throttle:5,1');
        Route::get('/auth/google/redirect', [AuthExtensionController::class, 'googleRedirect']);
        Route::post('/auth/google/callback', [AuthExtensionController::class, 'googleCallback']);
        Route::get('/auth/facebook/redirect', [AuthExtensionController::class, 'facebookRedirect']);
        Route::post('/auth/facebook/callback', [AuthExtensionController::class, 'facebookCallback']);
        Route::post('/auth/phone/send-otp', [AuthExtensionController::class, 'sendPhoneOtp'])->middleware('throttle:3,1');
        Route::post('/auth/phone/verify-otp', [AuthExtensionController::class, 'verifyPhoneOtp'])->middleware('throttle:10,1');
    });

    Route::middleware(['auth.principal', 'resolve.organization', 'api_client.routes', 'throttle:120,1'])->group(function (): void {
        Route::get('/user', fn () => request()->user()?->only(['id', 'name', 'email']));
        Route::patch('/user', [AuthController::class, 'updateProfile']);
        Route::get('/user/settings', [UserSettingsController::class, 'show']);
        Route::put('/user/settings', [UserSettingsController::class, 'update']);
        Route::post('/auth/logout', [AuthController::class, 'logout']);
        Route::get('/auth/sessions', [AuthController::class, 'sessions']);
        Route::get('/auth/recruitment-role', [AuthController::class, 'recruitmentRole']);
        Route::post('/auth/employer-service', [AuthController::class, 'activateEmployerService']);
        Route::delete('/auth/sessions/{token}', [AuthController::class, 'revokeSession'])->whereNumber('token');
        Route::post('/auth/email/verify', [AuthExtensionController::class, 'verifyEmail']);
        Route::post('/auth/email/resend', [AuthExtensionController::class, 'resendVerification'])->middleware('throttle:3,1');
        Route::get('/auth/identities', [AuthExtensionController::class, 'listIdentities']);
        Route::post('/auth/identities', [AuthExtensionController::class, 'linkIdentity']);
        Route::delete('/auth/identities/{identity}', [AuthExtensionController::class, 'unlinkIdentity'])->whereNumber('identity');
        Route::get('/providers/status', [ProviderStatusController::class, 'index']);
        Route::post('/providers/{provider}/test', [ProviderStatusController::class, 'test']);
        Route::get('/invitations', [InvitationController::class, 'index']);
        Route::post('/invitations', [InvitationController::class, 'store']);
        Route::delete('/invitations/{invitation}', [InvitationController::class, 'destroy'])->whereNumber('invitation');
        Route::get('/dashboard', DashboardController::class);
        Route::get('/platform/organizations', [PlatformController::class, 'organizations']);
        Route::get('/platform/admin/organizations', [PlatformAdminController::class, 'organizations']);
        Route::post('/platform/admin/organizations', [PlatformAdminController::class, 'storeOrganization']);
        Route::get('/platform/admin/organizations/{organization}', [PlatformAdminController::class, 'showOrganization'])->whereNumber('organization');
        Route::patch('/platform/admin/organizations/{organization}', [PlatformAdminController::class, 'updateOrganization'])->whereNumber('organization');
        Route::get('/platform/admin/organizations/{organization}/members', [PlatformAdminController::class, 'organizationMembers'])->whereNumber('organization');
        Route::post('/platform/admin/organizations/{organization}/members', [PlatformAdminController::class, 'addOrganizationMember'])->whereNumber('organization');
        Route::patch('/platform/admin/organizations/{organization}/members/{user}', [PlatformAdminController::class, 'updateOrganizationMember'])->whereNumber(['organization', 'user']);
        Route::delete('/platform/admin/organizations/{organization}/members/{user}', [PlatformAdminController::class, 'removeOrganizationMember'])->whereNumber(['organization', 'user']);
        Route::post('/media/uploads', [MediaController::class, 'upload']);
        Route::get('/media/uploads/{mediaUpload}', [MediaController::class, 'show'])->whereNumber('mediaUpload');
        Route::delete('/media/uploads/{mediaUpload}', [MediaController::class, 'destroy'])->whereNumber('mediaUpload');
        Route::get('/platform/me', [PlatformController::class, 'me']);
        Route::get('/platform/access-summary', [PlatformController::class, 'accessSummary']);
        Route::get('/platform/workflow-summary', [PlatformController::class, 'workflowSummary']);
        Route::get('/organization', [OrganizationController::class, 'show']);
        Route::patch('/organization', [OrganizationController::class, 'update']);
        Route::get('/organization/settings', [OrganizationController::class, 'settings']);
        Route::put('/organization/settings', [OrganizationController::class, 'updateSettings']);
        Route::get('/monitoring/health', [MonitoringController::class, 'health']);
        Route::get('/monitoring/incidents', [MonitoringController::class, 'incidents']);
        Route::post('/monitoring/incidents/{monitoringEvent}/resolve', [MonitoringController::class, 'resolveIncident'])->whereNumber('monitoringEvent');
        Route::get('/analytics/overview', [AnalyticsController::class, 'overview']);
        Route::get('/api-clients', [ApiClientController::class, 'index']);
        Route::post('/api-clients', [ApiClientController::class, 'store']);
        Route::post('/api-clients/{apiClient}/revoke', [ApiClientController::class, 'revoke'])->whereNumber('apiClient');
        Route::get('/projects', [ProjectController::class, 'index']);
        Route::patch('/tasks/{task}/status', [TaskController::class, 'updateStatus'])->whereNumber('task');
        Route::get('/users', [AccessController::class, 'users']);
        Route::post('/users', [AccessController::class, 'storeUser']);
        Route::get('/users/{user}', [AccessController::class, 'showUser'])->whereNumber('user');
        Route::patch('/users/{user}', [AccessController::class, 'updateUser'])->whereNumber('user');
        Route::delete('/users/{user}', [AccessController::class, 'removeUser'])->whereNumber('user');
        Route::post('/users/{user}/roles', [AccessController::class, 'assignRole'])->whereNumber('user');
        Route::delete('/users/{user}/roles/{role}', [AccessController::class, 'unassignRole'])->whereNumber(['user', 'role']);
        Route::get('/roles', [AccessController::class, 'roles']);
        Route::post('/roles', [AccessController::class, 'storeRole']);
        Route::get('/roles/{role}', [AccessController::class, 'showRole'])->whereNumber('role');
        Route::patch('/roles/{role}', [AccessController::class, 'updateRole'])->whereNumber('role');
        Route::delete('/roles/{role}', [AccessController::class, 'deleteRole'])->whereNumber('role');
        Route::get('/permissions/catalog', [AccessController::class, 'permissionsCatalog']);
        Route::get('/permissions', [AccessController::class, 'permissions']);
        Route::post('/permissions', [AccessController::class, 'storePermission']);
        Route::patch('/permissions/{permission}', [AccessController::class, 'updatePermission'])->whereNumber('permission');
        Route::delete('/permissions/{permission}', [AccessController::class, 'deletePermission'])->whereNumber('permission');
        Route::get('/teams', [TeamController::class, 'index']);
        Route::get('/teams/{team}', [TeamController::class, 'show'])->whereNumber('team');
        Route::post('/teams', [TeamController::class, 'store']);
        Route::post('/teams/{team}/members', [TeamController::class, 'addMember'])->whereNumber('team');
        Route::delete('/teams/{team}/members/{user}', [TeamController::class, 'removeMember'])->whereNumber(['team', 'user']);
        Route::get('/audit-logs', [AuditController::class, 'index']);
        Route::prefix('billing')->group(function (): void {
            Route::get('/plans', [BillingController::class, 'plans']);
            Route::get('/subscription', [BillingController::class, 'subscription']);
            Route::get('/usage', [BillingController::class, 'usage']);
            Route::get('/invoices', [BillingController::class, 'invoices']);
            Route::post('/subscription/plan', [BillingController::class, 'assignPlan']);
            Route::post('/subscription/cancel', [BillingController::class, 'cancel']);
            Route::post('/subscription/reactivate', [BillingController::class, 'reactivate']);
            Route::get('/settings', [BillingController::class, 'settings']);
            Route::put('/settings', [BillingController::class, 'updateSettings']);
        });
        Route::prefix('directory')->group(function (): void {
            Route::get('/{module}', [DirectoryController::class, 'index']);
            Route::post('/{module}', [DirectoryController::class, 'store']);
            Route::put('/{module}/{id}', [DirectoryController::class, 'update']);
            Route::delete('/{module}/{id}', [DirectoryController::class, 'destroy']);
        });
        Route::prefix('catalog')->group(function (): void {
            Route::get('/products/{product}/images', [ProductImageController::class, 'index'])->whereNumber('product');
            Route::post('/products/{product}/images', [ProductImageController::class, 'store'])->whereNumber('product');
            Route::delete('/products/{product}/images/{productImage}', [ProductImageController::class, 'destroy'])->whereNumber(['product', 'productImage']);
            Route::get('/{module}', [CatalogController::class, 'index']);
            Route::post('/{module}', [CatalogController::class, 'store']);
            Route::put('/{module}/{id}', [CatalogController::class, 'update']);
            Route::delete('/{module}/{id}', [CatalogController::class, 'destroy']);
        });
        Route::get('/inventory', [OperationsController::class, 'inventory']);
        Route::get('/inventory/movements', [OperationsController::class, 'inventoryMovements']);
        Route::post('/inventory/adjustments', [OperationsController::class, 'adjustInventory']);
        Route::get('/purchase-orders', [OperationsController::class, 'purchaseOrders']);
        Route::post('/purchase-orders', [OperationsController::class, 'storePurchaseOrder']);
        Route::post('/purchase-orders/{purchaseOrder}/receive', [OperationsController::class, 'receivePurchaseOrder']);
        Route::get('/sales-orders', [CommerceController::class, 'salesOrders']);
        Route::post('/sales-orders', [CommerceController::class, 'storeSalesOrder']);
        Route::get('/invoices', [CommerceController::class, 'invoices']);
        Route::post('/invoices', [CommerceController::class, 'storeInvoice']);
        Route::get('/reports/summary', [CommerceController::class, 'report']);
        Route::get('/reports/overview', [ReportsController::class, 'overview']);
        Route::get('/reports/recruitment', [JobSeekerController::class, 'report']);
        Route::get('/reports/marketplace', [MarketplaceAdminController::class, 'report']);
        Route::get('/reports/export', [ReportsController::class, 'export']);
        Route::get('/communications/inbox', [CommunicationsController::class, 'inbox']);
        Route::get('/communications/contacts/search', [CommunicationsController::class, 'searchContacts']);
        Route::get('/communications/contacts', [CommunicationsController::class, 'contacts']);
        Route::post('/communications/contacts', [CommunicationsController::class, 'storeContact']);
        Route::patch('/communications/contacts/{contact}', [CommunicationsController::class, 'updateContact'])->whereNumber('contact');
        Route::delete('/communications/contacts/{contact}', [CommunicationsController::class, 'destroyContact'])->whereNumber('contact');
        Route::get('/communications/drafts', [CommunicationsController::class, 'drafts']);
        Route::get('/communications/messages', [CommunicationsController::class, 'messages']);
        Route::get('/communications/messages/{message}', [CommunicationsController::class, 'showMessage'])->whereNumber('message');
        Route::post('/communications/messages', [CommunicationsController::class, 'compose']);
        Route::patch('/communications/messages/{message}', [CommunicationsController::class, 'updateMessage'])->whereNumber('message');
        Route::delete('/communications/messages/{message}', [CommunicationsController::class, 'destroyMessage'])->whereNumber('message');
        Route::post('/communications/messages/{message}/send', [CommunicationsController::class, 'send'])->whereNumber('message');
        Route::get('/communications/providers', [CommunicationsController::class, 'providers']);
        Route::get('/communications/mailing-lists', [CommunicationsController::class, 'mailingLists']);
        Route::post('/communications/mailing-lists', [CommunicationsController::class, 'storeMailingList']);
        Route::patch('/communications/mailing-lists/{mailingList}', [CommunicationsController::class, 'updateMailingList'])->whereNumber('mailingList');
        Route::delete('/communications/mailing-lists/{mailingList}', [CommunicationsController::class, 'destroyMailingList'])->whereNumber('mailingList');
        Route::get('/communications/mailing-lists/{mailingList}/members', [CommunicationsController::class, 'mailingListMembers'])->whereNumber('mailingList');
        Route::post('/communications/mailing-lists/{mailingList}/members', [CommunicationsController::class, 'addMailingListMembers'])->whereNumber('mailingList');
        Route::delete('/communications/mailing-lists/{mailingList}/members/{member}', [CommunicationsController::class, 'removeMailingListMember'])->whereNumber(['mailingList', 'member']);
        Route::get('/analytics/traffic', [AnalyticsEventsController::class, 'traffic']);
        Route::post('/analytics/events', [AnalyticsEventsController::class, 'store']);
        Route::get('/monitoring/logs', [MonitoringLogsController::class, 'index']);
        Route::post('/monitoring/logs', [MonitoringLogsController::class, 'store']);
        Route::get('/notifications', [CommerceController::class, 'notifications']);
        Route::post('/notifications', [CommerceController::class, 'storeNotification']);
        Route::post('/notifications/read-all', [CommerceController::class, 'markAllNotificationsRead']);
        Route::post('/notifications/{notification}/read', [CommerceController::class, 'readNotification']);
        Route::prefix('farm')->group(function (): void {
            Route::get('/{module}', [FarmController::class, 'index']);
            Route::post('/{module}', [FarmController::class, 'store']);
            Route::put('/{module}/{id}', [FarmController::class, 'update']);
            Route::delete('/{module}/{id}', [FarmController::class, 'destroy']);
        });
        Route::prefix('crop')->group(function (): void {
            Route::get('/{module}', [CropController::class, 'index']);
            Route::post('/{module}', [CropController::class, 'store']);
            Route::put('/{module}/{id}', [CropController::class, 'update']);
            Route::delete('/{module}/{id}', [CropController::class, 'destroy']);
        });
        Route::prefix('soil')->group(function (): void {
            Route::get('/{module}', [SoilController::class, 'index']);
            Route::post('/{module}', [SoilController::class, 'store']);
            Route::put('/{module}/{id}', [SoilController::class, 'update']);
            Route::delete('/{module}/{id}', [SoilController::class, 'destroy']);
        });
        Route::prefix('diagnosis')->group(function (): void {
            Route::get('/requests', [DiagnosisRequestController::class, 'index']);
            Route::post('/requests', [DiagnosisRequestController::class, 'store']);
            Route::get('/requests/{id}', [DiagnosisRequestController::class, 'show']);
            Route::get('/{module}', [DiagnosisController::class, 'index']);
            Route::post('/{module}', [DiagnosisController::class, 'store']);
            Route::put('/{module}/{id}', [DiagnosisController::class, 'update']);
            Route::delete('/{module}/{id}', [DiagnosisController::class, 'destroy']);
        });
        Route::prefix('training')->group(function (): void {
            Route::get('/enrollments', [TrainingController::class, 'enrollments']);
            Route::post('/enrollments', [TrainingController::class, 'enroll']);
            Route::post('/progress/complete', [TrainingController::class, 'completeLesson']);
            Route::get('/{module}', [TrainingController::class, 'index']);
            Route::post('/{module}', [TrainingController::class, 'store']);
            Route::put('/{module}/{id}', [TrainingController::class, 'update']);
            Route::delete('/{module}/{id}', [TrainingController::class, 'destroy']);
        });
        Route::prefix('library')->group(function (): void {
            Route::get('/search', [LibraryController::class, 'search']);
            Route::get('/crop-knowledge/tree', [CropKnowledgeLibraryBrowseController::class, 'tree']);
            Route::get('/crop-knowledge/items/{itemId}', [CropKnowledgeLibraryBrowseController::class, 'show'])->whereNumber('itemId');
            Route::get('/{module}', [LibraryController::class, 'index']);
            Route::post('/{module}', [LibraryController::class, 'store']);
            Route::put('/{module}/{id}', [LibraryController::class, 'update']);
            Route::delete('/{module}/{id}', [LibraryController::class, 'destroy']);
        });
        Route::prefix('ai')->middleware('throttle:ai-org')->group(function (): void {
            Route::get('/provider', [AiController::class, 'provider']);
            Route::get('/usage', [AiController::class, 'usage']);
            Route::get('/requests', [AiController::class, 'index']);
            Route::post('/requests', [AiController::class, 'store']);
            Route::get('/requests/{id}', [AiController::class, 'show'])->whereNumber('id');
            Route::post('/requests/{id}/cancel', [AiController::class, 'cancel'])->whereNumber('id');
            Route::get('/assistant/conversations', [AiAssistantController::class, 'index']);
            Route::post('/assistant/conversations', [AiAssistantController::class, 'store']);
            Route::get('/assistant/conversations/{conversation}', [AiAssistantController::class, 'show'])->whereNumber('conversation');
            Route::post('/assistant/conversations/{conversation}/messages', [AiAssistantController::class, 'message'])->whereNumber('conversation');
            Route::post('/assistant/conversations/{conversation}/archive', [AiAssistantController::class, 'archive'])->whereNumber('conversation');
            Route::delete('/assistant/conversations/{conversation}', [AiAssistantController::class, 'destroy'])->whereNumber('conversation');
            Route::post('/assistant/actions/execute', [AiAssistantController::class, 'executeAction']);
            Route::post('/vision/uploads', [AiVisionController::class, 'upload']);
            Route::get('/vision/uploads/{upload}', [AiVisionController::class, 'show'])->whereNumber('upload');
        });
        Route::prefix('marketing')->group(function (): void {
            Route::get('/dashboard', [MarketingController::class, 'dashboard']);
            Route::get('/campaigns', [MarketingController::class, 'campaigns']);
            Route::post('/campaigns', [MarketingController::class, 'storeCampaign']);
            Route::get('/campaigns/{campaign}', [MarketingController::class, 'showCampaign'])->whereNumber('campaign');
            Route::patch('/campaigns/{campaign}', [MarketingController::class, 'updateCampaign'])->whereNumber('campaign');
            Route::delete('/campaigns/{campaign}', [MarketingController::class, 'destroyCampaign'])->whereNumber('campaign');
            Route::post('/campaigns/{campaign}/schedule', [MarketingController::class, 'scheduleCampaign'])->whereNumber('campaign');
            Route::post('/campaigns/{campaign}/cancel', [MarketingController::class, 'cancelCampaign'])->whereNumber('campaign');
            Route::get('/campaigns/{campaign}/preview', [MarketingController::class, 'previewCampaign'])->whereNumber('campaign');
            Route::post('/campaigns/{campaign}/test-send', [MarketingController::class, 'testSendCampaign'])->whereNumber('campaign');
            Route::post('/campaigns/{campaign}/process', [MarketingController::class, 'processCampaign'])->whereNumber('campaign');
            Route::get('/campaigns/{campaign}/snapshots', [MarketingController::class, 'snapshots'])->whereNumber('campaign');
            Route::get('/segments', [MarketingController::class, 'segments']);
            Route::post('/segments', [MarketingController::class, 'storeSegment']);
            Route::get('/templates', [MarketingController::class, 'templates']);
            Route::post('/templates', [MarketingController::class, 'storeTemplate']);
            Route::get('/consents', [MarketingController::class, 'consents']);
            Route::post('/consents', [MarketingController::class, 'storeConsent']);
            Route::get('/suppressions', [MarketingController::class, 'suppressions']);
            Route::post('/suppressions', [MarketingController::class, 'storeSuppression']);
            Route::get('/deliveries', [MarketingController::class, 'deliveries']);
        });
        Route::prefix('job-seekers')->group(function (): void {
            // M21 recruitment CRM. Profiles are user-global; vacancy/matching stays on /jobs/*.
            Route::get('/', [JobSeekerController::class, 'index']);
            Route::get('/me', [JobSeekerProfileController::class, 'showMine']);
            Route::put('/me', [JobSeekerProfileController::class, 'upsertMine']);
            Route::patch('/me', [JobSeekerProfileController::class, 'upsertMine']);
            Route::delete('/me', [JobSeekerProfileController::class, 'destroyMine']);
            Route::get('/me/cv', [JobSeekerProfileController::class, 'downloadCv']);
            Route::post('/me/cv', [JobSeekerProfileController::class, 'uploadCv']);
            Route::get('/me/primary-qualification', [JobSeekerProfileController::class, 'downloadPrimaryQualification']);
            Route::post('/me/primary-qualification', [JobSeekerProfileController::class, 'uploadPrimaryQualification']);
            Route::get('/{jobSeeker}', [JobSeekerController::class, 'show'])->whereNumber('jobSeeker');
            Route::get('/{jobSeeker}/cv', [JobSeekerController::class, 'downloadCv'])->whereNumber('jobSeeker');
            Route::patch('/{jobSeeker}', [JobSeekerController::class, 'update'])->whereNumber('jobSeeker');
            Route::patch('/{jobSeeker}/status', [JobSeekerController::class, 'updateStatus'])->whereNumber('jobSeeker');
            Route::post('/{jobSeeker}/notes', [JobSeekerController::class, 'storeNote'])->whereNumber('jobSeeker');
            Route::get('/{jobSeeker}/notes', [JobSeekerController::class, 'notes'])->whereNumber('jobSeeker');
            Route::get('/{jobSeeker}/history', [JobSeekerController::class, 'history'])->whereNumber('jobSeeker');
        });
        Route::prefix('market')->group(function (): void {
            Route::get('/listings', [MarketplacePublicController::class, 'listings']);
            Route::get('/listings/{listing}', [MarketplacePublicController::class, 'show'])->whereNumber('listing');
            Route::get('/categories', [MarketplacePublicController::class, 'categories']);
            Route::get('/units', [MarketplacePublicController::class, 'units']);
            Route::get('/my-listings', [MarketplaceListingController::class, 'myListings']);
            Route::get('/my-listings/{listing}', [MarketplaceListingController::class, 'showMine'])->whereNumber('listing');
            Route::post('/listings', [MarketplaceListingController::class, 'store']);
            Route::patch('/listings/{listing}', [MarketplaceListingController::class, 'update'])->whereNumber('listing');
            Route::delete('/listings/{listing}', [MarketplaceListingController::class, 'destroy'])->whereNumber('listing');
            Route::post('/listings/{listing}/submit', [MarketplaceListingController::class, 'submit'])->whereNumber('listing');
            Route::post('/listings/{listing}/unpublish', [MarketplaceListingController::class, 'unpublish'])->whereNumber('listing');
            Route::post('/listings/{listing}/request-contact-access', [MarketplaceListingController::class, 'requestContactAccess'])->whereNumber('listing');
            Route::post('/contact-access-orders/{order}/pay', [MarketplaceListingController::class, 'payContactAccess'])->whereNumber('order');
            Route::get('/contact-access-orders/{order}/seller-contact', [MarketplaceListingController::class, 'sellerContact'])->whereNumber('order');
            Route::get('/my-entitlements', [MarketplaceListingController::class, 'myEntitlements']);
        });
        Route::prefix('admin/market')->group(function (): void {
            Route::get('/listings', [MarketplaceAdminController::class, 'listings']);
            Route::post('/listings/{listing}/approve', [MarketplaceAdminController::class, 'approve'])->whereNumber('listing');
            Route::post('/listings/{listing}/reject', [MarketplaceAdminController::class, 'reject'])->whereNumber('listing');
            Route::post('/listings/{listing}/suspend', [MarketplaceAdminController::class, 'suspend'])->whereNumber('listing');
            Route::get('/categories', [MarketplaceAdminController::class, 'categories']);
            Route::post('/categories', [MarketplaceAdminController::class, 'storeCategory']);
        });
        Route::prefix('jobs')->group(function (): void {
            Route::get('/talent/me', [JobsTalentController::class, 'showMine']);
            Route::put('/talent/me', [JobsTalentController::class, 'upsert']);
            Route::get('/talent/me/cv', [JobsTalentController::class, 'downloadCv']);
            Route::post('/talent/me/cv', [JobsTalentController::class, 'uploadCv']);
            Route::post('/talent/me/cv/parse', [JobsTalentController::class, 'parseCv']);
            Route::get('/talent/me/contact-requests', [JobsTalentController::class, 'myContactRequests']);
            Route::get('/seekers', [JobsEmployerController::class, 'searchSeekers']);
            Route::get('/seekers/{jobSeeker}', [JobsEmployerController::class, 'showSeeker'])->whereNumber('jobSeeker');
            Route::get('/seekers/{jobSeeker}/photo', [JobsEmployerController::class, 'seekerPhoto'])->whereNumber('jobSeeker');
            Route::post('/seekers/{jobSeeker}/contact-requests', [JobsEmployerController::class, 'requestSeekerContact'])->whereNumber('jobSeeker');
            Route::get('/candidates', [JobsEmployerController::class, 'search']);
            Route::post('/candidates/match', [JobsEmployerController::class, 'match']);
            Route::get('/candidates/{talentProfile}', [JobsEmployerController::class, 'show'])->whereNumber('talentProfile');
            Route::post('/candidates/{talentProfile}/contact-requests', [JobsEmployerController::class, 'requestContact'])->whereNumber('talentProfile');
            Route::post('/contact-requests/{contactRequestId}/pay', [JobsEmployerController::class, 'payContact'])->whereNumber('contactRequestId');
            Route::get('/contact-requests/{contactRequestId}/contact', [JobsEmployerController::class, 'unlockedContact'])->whereNumber('contactRequestId');
            Route::get('/contact-requests/{contactRequestId}/cv', [JobsEmployerController::class, 'unlockedCv'])->whereNumber('contactRequestId');
            Route::post('/contact-requests/{contactRequestId}/hire', [JobsEmployerController::class, 'markHired'])->whereNumber('contactRequestId');
            Route::post('/reports', [JobsEmployerController::class, 'report']);
        });
        Route::prefix('beekeeping')->group(function (): void {
            Route::get('/profile', [BeekeepingController::class, 'profile']);
            Route::put('/profile', [BeekeepingController::class, 'upsertProfile']);
            Route::get('/apiaries', [BeekeepingController::class, 'apiaries']);
            Route::post('/apiaries', [BeekeepingController::class, 'storeApiary']);
            Route::get('/apiaries/{apiary}/hives', [BeekeepingController::class, 'hives'])->whereNumber('apiary');
            Route::post('/apiaries/{apiary}/hives', [BeekeepingController::class, 'storeHive'])->whereNumber('apiary');
            Route::post('/hives/{hive}/inspections', [BeekeepingController::class, 'storeInspection'])->whereNumber('hive');
            Route::get('/hives/{hive}/treatments', [BeekeepingController::class, 'treatments'])->whereNumber('hive');
            Route::post('/hives/{hive}/treatments', [BeekeepingController::class, 'storeTreatment'])->whereNumber('hive');
            Route::get('/hives/{hive}/feedings', [BeekeepingController::class, 'feedings'])->whereNumber('hive');
            Route::post('/hives/{hive}/feedings', [BeekeepingController::class, 'storeFeeding'])->whereNumber('hive');
            Route::get('/hives/{hive}/production-records', [BeekeepingController::class, 'productionRecords'])->whereNumber('hive');
            Route::post('/hives/{hive}/production-records', [BeekeepingController::class, 'storeProductionRecord'])->whereNumber('hive');
            Route::get('/calendar/tasks', [BeekeepingController::class, 'calendar']);
            Route::post('/calendar/tasks', [BeekeepingController::class, 'storeCalendarTask']);
            Route::get('/pollination/plants', [BeekeepingController::class, 'plants']);
            Route::post('/pollination/plants', [BeekeepingController::class, 'storePlant']);
            Route::get('/knowledge/topics', [BeekeepingController::class, 'knowledgeTopics']);
        });
    });
});
