export * from './types'
export * from './client'
export * from './auth'
export * from './dashboard'
export * from './organizations'
export * from './platform'
export * from './billing'
export * from './users'
export * from './teams'
export * from './notifications'
export * from './ai'
export * from './modules'

// Backward-compatible aliases used by existing pages.
export { unwrapModuleRows, modulePaginationMeta } from './client'
